### ISSUE TITLE
Question about training time.

### ISSUE THREAD

**Issue by HansenHuang0823** [xuduo35/MakeLongVideo#2]
从Make A Video的issue中看到你只用了两个3090来训练就取得了这么好的效果，很厉害！请问目前这个效果是在2x3090上训练了多长时间呢？

**Comment by xuduo35** [comment]
大概先在128x128训了一周，然后256x256训练了三周多，我的卡经常干别的，所以是断断续续训的，loss其实还在降，我没训完，这是中间结果。按循环次数算比较可靠。
