### ISSUE TITLE
Watermark handling

### ISSUE THREAD

**Issue by JHLew** [xuduo35/MakeLongVideo#4]
Hi, thank you for sharing your implementation.

I figured that all the videos from the WebVid dataset have watermarks.

I believe they would critically influence the training of video generative models, inevitably generating watermarks.

I do spy some watermarks from the samples you have shared, but was surprised that some of them didn't have watermarks.

Could there be any tips that you could share to avoid watermark generation?

**Comment by xuduo35** [comment]
Some methods you can try
1. Add some videos without watermark into training data, add some special text mark for them distinguishing with webvid videos. At inference stage, add special text mark  into negative prompt.
2. Or finetune with videos-no-watermark, ~1w could be enough according to zeroscope. https://huggingface.co/cerspense/zeroscope_v2_576w
3. Train on 256x256 and inference in 384x384, but result could get worse.

**Comment by JHLew** [comment]
Thanks for sharing!
