### ISSUE TITLE
How should I use it

### ISSUE THREAD

**Issue by zsh123abc** [xuduo35/MakeLongVideo#7]
How should I use it

**Comment by xuduo35** [comment]
Refer to Readme.md

**Comment by zsh123abc** [comment]
> Refer to Readme.md

May I ask if the Laion400m dataset is required

**Comment by xuduo35** [comment]
No. Only video dataset is enough.

**Comment by zsh123abc** [comment]
> No. Only video dataset is enough.

I need to generate a video. Do I need to train a model myself

**Comment by xuduo35** [comment]
There is a pretrained weights you can try https://github.com/xuduo35/MakeLongVideo#inference. Just for fun, it's far from good.

**Comment by zsh123abc** [comment]
> There is a pretrained weights you can try https://github.com/xuduo35/MakeLongVideo#inference. Just for fun, it's far from good.

I want to generate a video, but I'm not very proficient in operation

**Comment by xuduo35** [comment]
Zeroscope is an option for you, https://huggingface.co/spaces/fffiloni/zeroscope

**Comment by zsh123abc** [comment]
> Zeroscope is an option for you, https://huggingface.co/spaces/fffiloni/zeroscope

Thank you. If only I could deploy it locally for use

**Comment by zsh123abc** [comment]
> Zeroscope is an option for you, https://huggingface.co/spaces/fffiloni/zeroscope

I am trying to deploy this project locally. Is this project deployable

**Comment by zsh123abc** [comment]
> Zeroscope is an option for you, https://huggingface.co/spaces/fffiloni/zeroscope

Do you have time to guide me on how to deploy，Thank you

**Comment by xuduo35** [comment]
Basic steps:
1. git clone it
2. pip install requirements.txt
3. python app.py
I'm afraid I have no time to go through all the details for you, you should learn all the skills yourself.
