### ISSUE TITLE
Not able to do inference.

### ISSUE THREAD

**Issue by Ajeet-kumar1** [xuduo35/MakeLongVideo#9]
When I am running given inference command it shows
```
  File "/home/ajeet/MakeLongVideo/makelongvideo/models/unet_blocks.py", line 64, in get_down_block
    raise ValueError(f"{down_block_type} does not exist.")
ValueError: ResnetDownsampleBlock2D does not exist.
```

@xuduo35 Can you please look. I have installed all requirements and downloaded checkpoints

**Comment by xuduo35** [comment]
I don't work on this project some months. But I reinstall a clean env and didn't meet this issue. Can you paste the full trace stack?
